name: Docker (Windows)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * 3'
  push:
    branches: [ "master" ]
    paths-ignore: [ "linux/**" ]
  pull_request:
    branches: [ "master" ]

env:
  REGISTRY: ghcr.io

jobs:
  build-windows:
    strategy:
      matrix:
        image:
          - tag: ltsc2022
            runner: windows-2022
            dockerfile: Dockerfile
            base: 4.8.1-windowsservercore-ltsc2022
          - tag: vs2026
            runner: windows-2025
            dockerfile: vs2026.Dockerfile
            base: 4.8.1-windowsservercore-ltsc2025
    runs-on: ${{ matrix.image.runner }}
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: image_name
        name: Make image name lowercase
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ github.repository }}

      - name: Build Docker image
        run: |
          docker build . --pull --file ${{ matrix.image.dockerfile }} --tag ${{ env.REGISTRY }}/${{ steps.image_name.outputs.lowercase }}:${{ matrix.image.tag }} --build-arg BASE=${{ matrix.image.base }} --build-arg ARIAL_TTF_URL=${{ secrets.ARIAL_TTF_URL }}
        working-directory: windows

      - name: Push Docker image
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          docker push ${{ env.REGISTRY }}/${{ steps.image_name.outputs.lowercase }}:${{ matrix.image.tag }}
        working-directory: windows
